### ISSUE TITLE
Research hard-coded properties excluded from current view

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#15]
## Current
Restrictive Declaration: omppropid in('M404', 'B591', 'B595')
Greenstreet: omppropid in('XZ475')

## Commented Out
Unmapped: gispropnum in('BT02', 'BT04')

**Comment by GeoDan87** [comment]
Additional Sites from the GIStoPIP csv file shared on 2/16

PropNum | Prop ID | District | AMPSDistrict | SourceFC
-- | -- | -- | -- | --
Q516 | Q516 | NULL | 2 | Property
MT12 | MT12 | NULL | 1 | Property
Q519 | Q519 | NULL | 13 | Property
X370 | X370 | NULL | 15 | Property
Q517 | Q517 | NULL | 8 | Property
MT13 | MT13 | NULL | 2 | Property
BT21 | BT21 | NULL | 1 | RestrictiveDeclarationSite

**Comment by GeoDan87** [comment]
Adding B537 into the mix as it exists in both Property and Unmapped.

**Comment by MEFParks** [comment]
> Adding B537 into the mix as it exists in both Property and Unmapped.

We resolved that issue in prod last week. B537 was removed from the Unmapped  table so there is no longer a conflict

**Comment by MEFParks** [comment]
> Additional Sites from the GIStoPIP csv file shared on 2/16
> 
> PropNum	Prop ID	District	AMPSDistrict	SourceFC
> Q516	Q516	NULL	2	Property
> MT12	MT12	NULL	1	Property
> Q519	Q519	NULL	13	Property
> X370	X370	NULL	15	Property
> Q517	Q517	NULL	8	Property
> MT13	MT13	NULL	2	Property
> BT21	BT21	NULL	1	RestrictiveDeclarationSite

We'll need to ask Peter why these aren't pushing (if we can't figure it out ourselves from the old sync documentation). I know they set up some restrictions so properties with limited information don't get pushed through... but I'm not sure what that criteria is and how/why those are hung up. I hope it's not because they have null district (a field nobody uses now).

**Comment by MEFParks** [comment]
> ## Current
> Restrictive Declaration: omppropid in('M404', 'B591', 'B595')
> Greenstreet: omppropid in('XZ475')
> 
> ## Commented Out
> Unmapped: gispropnum in('BT02', 'BT04')


BT02 and BT04 are due to be deleted from the Unmapped (I re-mapped the whole layer and made recommendations on how to resolve all the issues with this table, but it got stuck with the Greenstreet MOU, on Antonios' desk for the property layer stuff, and there wasn't much will from GIS to push it forward). We could delete them from Unmapped now if we wanted to and not hardcode them out as there are representations for these sites on the REDEC layer that would push in to allsites.

XZ475:

There are two records on the Greenstreet layer with OMPPROPID= XZ475, one is a retired record that was the old "dash" GS number. We could make the omppropid back to the old dash number for the retired value (SYSTEM= X128-XZ475) and mark it as PIP_Rateable= 0 that would get rid of the conflict and we wouldn't have to hardcode.

Restrictive Declaration: omppropid in('M404', 'B591', 'B595'):

So it looks like Allsites is pulling these values now from property M404 and B591 have representations on the REDEC layer, B595 does not (it may have at one point, necessitating the hardcoding). This is an issue with the REDEC layer because Antonios has some duplicate records across tables for his own reasons. Is there a way instead of hardcoding that we can give REDEC primacy over Property so we consume those records when their is a conflict, but as soon as Antonios deletes records off of the REDEC table we start consuming the Property level records? Just trying to think of how to get around hardcoding, but it might just be easier to hardcode the few cases.

In general, though, we should probably keep in mind that there will likely be more cases where a site shows up on multiple layers (most likely being REDEC and Property)

**Comment by GeoDan87** [comment]
We could keep going and then compare the records in new allsites vs the current allsites

**Comment by GeoDan87** [comment]
Pinged Peter on 3/16

**Comment by GeoDan87** [comment]
@MEFParks i missed that bit about the greenstreet above. I think that that sounds like a good idea to set it's omppropid to the dash number.

**Comment by GeoDan87** [comment]
Closing this issue. Some exclusions are currently made based on missing data (district). This shouldn't exclude records from the new process unless the [prop id] is null. All hard coded records have been removed.
