### ISSUE TITLE
Greenstreet where clause in vw_pip_compatible...

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#40]
https://github.com/NYCParks-data/PIP_Sync/blob/master/vw_pip_compatible_inspected_sites.sql#L78-L79

Lines 78 and 79 here (github add to issue function not working for me now)

where --omppropid not like 'XZ475' or
	  retired like 'False'

Can we take the hard code out now, and why are we filtering our retired?

**Comment by GeoDan87** [comment]
@MEFParks it's weird that it's not working for you. I did remove that hardcoded value and I kept the retired filter because that was in the original query. I think it would be wise to remove the retired filter because my understanding was that that column would be replaced outright by featurestatus. 

Note that this will add 544 records to tbl_ref_allsites and tbl_pip_allsites. Maybe this isn't such a big deal because you can just keep the records as unrated and bulk update the Reason Not Rated.

**Comment by GeoDan87** [comment]
Say the word and it's removed.

**Comment by GeoDan87** [comment]
@MEFParks, just following up on this. I got rid of the retired logic, maybe you'll stumble across these in your review. Do you think it's okay the way it is now?
