### ISSUE TITLE
Using Structure Function to get records from Structures

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#42]
https://github.com/NYCParks-data/PIP_Sync/blob/32b77c6927a53a9852d6b34857814549d64fa541/vw_pip_compatible_inspected_sites.sql#L173

Is this still an open question? Not sure how we resolved getting records like BAC that Public Programs don't want to call rec or nature center

**Comment by GeoDan87** [comment]
That particular exception still confuses me. It's a site we do programming at, but it isn't under our jurisdiction? How did we end up inspecting it?

**Comment by MEFParks** [comment]
It's technically a concession that we inspect as a Rec Center for Planning. That's why Public Programs doesn't include it on their list (and why it lives in structures). We just need it in Allsites so we can continue to inspect.

**Comment by GeoDan87** [comment]
My preference would be to add a new value to the structure function table to accommodate this case. Paul and I had added Food Service and Retail as an attempt to get at concession agreements. What do you think? How would you categorize it?

https://github.com/NYCParks-data/Structures/wiki/Definitions

**Comment by MEFParks** [comment]
Alex said:  "It is unique in that it is concession but otherwise has the trappings of a rec center "

https://bklanyc.com/about-us/

Can we use the function Concession or is that too broad?  Rec Center Concession?

**Comment by GeoDan87** [comment]
I mean, shouldn't we just make it a Recreation Center? I guess that's a question for Ricardo or Patricia rather than you. I'm also curious how this differs from a Community Center.

Paul and I avoided building concession into the function because the idea was to have it be broad. In theory, this would mean that every exception gets a duplicative exception [structurefunction]. It seems to me like ideally we'd would attribute or get information from the concession database (they use their own ids).
